# this corresponds to the default config
train:
  dataset_path: MajorTOM
  s2_patch_size: 256
  s2_bands:
    - "B02"
    - "B03"
    - "B04"
    - "B05"
    - "B06"
    - "B07"
    - "B08"
    - "B8A"
    - "B11"
    - "B12"
  checkpointing: true
student:
  drop_path_rate: 0.1
  arch: vit_base
